# Site settings
title: 三尺墨
motto: 帘外五更风雨冷，案头三尺笔墨浓
email: jchengpeng@163.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "https://jchengpeng.github.io" # the subpath of your site, e.g. /blog/
url: "https://jchengpeng.github.io" # the base hostname & protocol for your site
twitter_username: jchengpeng
github_username:  jchengpeng

# Build settings
markdown: kramdown
